# This is a basic workflow to help you get started with Actions

name: Sensuflow CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sensuflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Service containers to run with `sensu-flow`
    services:
      # Label used to access the service container
      sensu-backend:
        # Docker Hub image
        image: jspaleta/sensu-backend-github-action-service
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sensuflow with defaults and no sanity checking
      uses: ./
      id: defaults
      with:
        sensu_backend_url: ws://sensu-backend:8080
        sensu_user: admin
        sensu_password: ${{ secrets.SENSU_ADMIN_PASSWORD }} 
        disable_sanity_checks: true

    - name: Sensuflow with optional settings
      uses: ./
      id: options
      with:
        sensu_backend_url: ws://sensu-backend:8080
        sensu_user: admin
        sensu_password: ${{ secrets.SENSU_ADMIN_PASSWORD }} 
        namespaces_dir: ci-namespaces
        matching_label: "sensu.io/workflow"
        matching_condition: "== ci_action"


